# 示例配置文件
# 重命名为 config.yaml 并根据需要修改参数

# 数据下载配置
data_download:
  source_url: "https://raw.githubusercontent.com/datawhalechina/self-llm/master/dataset"
  data_file: "huanhuan.json"

# 数据处理配置
data_process:
  max_samples: null  # null表示处理全部数据，也可以设置为具体数字如1000
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1

# 模型训练配置
model_training:
  config_file: "training/huanhuan_config_fast.yaml"
  base_model: "qwen2.5:0.5b"
  output_dir: "training/models/huanhuan_fast"

# 模型部署配置
model_deployment:
  base_model: "qwen2.5:0.5b"
  modelfile: "deployment/Modelfile.huanhuan"
  model_name: "huanhuan_fast"

# Web界面配置
web_interface:
  port: 8501

# MCP服务器配置
mcp_server:
  port: 3141